### ISSUE TITLE
maybe mislabled defect probability of some images

### ISSUE THREAD

**Issue by chuanglaipv** [zae-bayern/elpv-dataset#1]
Thanks for you guys did a great work!
But I found some images looks to be defected (such as 443,446, etc.) are classifid to  probability of 1.0, were they mislabled?
Regards!

**Comment by sergiud** [comment]
I'm glad you found our work to be useful.

It is possible that some images are not labeled as you might expect. Given there are no ground truth measurements, the labels are derived from the experience of the expert labeler.

How did you determine the images are mislabeled and what defect probabilities are you suggesting instead?

**Comment by chuanglaipv** [comment]
Thanks for your reply.
![maybe Mislabeled](https://user-images.githubusercontent.com/11863306/56735586-693ff580-6798-11e9-96b6-72befee6a5dc.PNG)
As shown, all images were labeled to 100% defect probability. I highlight some images maybe mislabeled, since I found no crack or dirty,  I am not expert, I just want to make sense of what defects on these cells. Thanks a lot.

**Comment by sergiud** [comment]
The defect probability is not defined by whether the solar cell contains any cracks, but in terms whether the cell contains any surface abnormalities that are known to cause power loss now or in the future. Please, make sure to take a look at the dataset description in one of our publications for more information.
