### ISSUE TITLE
Kontakt

### ISSUE THREAD

**Issue by admin-zae** [zae-bayern/elpv-dataset#5]
Hallo, ich weiß das hier ist nicht der optimale Weg zur Kontaktaufnahme, finde aber keinen besseren Weg dir zu schreiben.
Kannst du mir mal eine Mail an Oliver.Glass@zae-bayern.de schreiben? Ich wollte den Github Account "reaktivieren" und habe hier dein Repository gesehen. 

Danke und VG, Oliver Glaß

**Comment by sergiud** [comment]
Bitte schreibe mir an meine FAU-E-Mail Adresse (diese findest u.a. in entsprechenden Publikationen). Ich verstehe leider nicht wirklich worum es hier geht.
